version: '3.8'

services:
  sio_test:
    user: app
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
    ports:
      - "8337:8337"
    volumes:
      - ./systemeio_test:/app:rw
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://app:password@postgres:5432/app?serverVersion=13&charset=utf8"
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  redis:
#    image: redis:6
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sio_test

volumes:
  postgres_data:
  redis_data: